from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from .schemas import (
    DetailedInnovationSpec,
    GeneratedModule,
    GeneratedProject,
    P2PModelSpec,
    to_dict,
)
from .utils import ensure_dir


class ProjectAssembler:
    """Assemble generated modules into a complete standalone project.

    Creates directory structure, configs, entry point, tests, and runs
    integration tests.
    """

    def __init__(self, project_root: str):
        self.project_root = ensure_dir(project_root)

    def assemble_project(
        self,
        modules: List[GeneratedModule],
        model_spec: P2PModelSpec,
        innovation_spec: DetailedInnovationSpec,
        grid_case: str = "ieee33",
        experiment_config: Optional[Dict[str, Any]] = None,
    ) -> GeneratedProject:
        """Assemble all modules into a complete project."""
        project_dir = self.project_root
        src_dir = ensure_dir(os.path.join(project_dir, "src"))
        config_dir = ensure_dir(os.path.join(project_dir, "configs"))
        tests_dir = ensure_dir(os.path.join(project_dir, "tests"))
        outputs_dir = ensure_dir(os.path.join(project_dir, "outputs"))
        docs_dir = ensure_dir(os.path.join(project_dir, "docs"))

        grid_dir = ensure_dir(os.path.join(src_dir, "grid"))
        market_dir = ensure_dir(os.path.join(src_dir, "market"))
        algorithm_dir = ensure_dir(os.path.join(src_dir, "algorithm"))
        utils_dir = ensure_dir(os.path.join(src_dir, "utils"))

        for d in [src_dir, grid_dir, market_dir, algorithm_dir, utils_dir]:
            init_path = os.path.join(d, "__init__.py")
            if not os.path.exists(init_path):
                with open(init_path, "w", encoding="utf-8") as f:
                    f.write('"""Generated by Energy Trading Lab."""\n')

        base_modules = [m for m in modules if m.module_type in ("grid_model", "market_env")]
        algo_modules = [m for m in modules if m not in base_modules]

        module_paths = {}
        for module in modules:
            if module.module_type == "grid_model":
                target_dir = grid_dir
            elif module.module_type == "market_env":
                target_dir = market_dir
            else:
                target_dir = algorithm_dir

            file_path = os.path.join(target_dir, module.file_path)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(module.code)
            module_paths[module.module_name] = file_path

        self._write_utils(utils_dir)
        self._write_configs(config_dir, grid_case, model_spec, innovation_spec, experiment_config)
        self._write_runner(src_dir, innovation_spec, grid_case)
        self._write_requirements(project_dir)
        self._write_readme(project_dir, model_spec, innovation_spec, grid_case)
        self._write_tests(tests_dir, innovation_spec, grid_case)

        integration_passed, integration_log = self._run_integration_test(
            project_dir, innovation_spec
        )

        algo_family = innovation_spec.base_algorithm_family
        project = GeneratedProject(
            project_dir=project_dir,
            modules=modules,
            algorithm_family=algo_family,
            innovation_mode=innovation_spec.innovation_mode,
            integration_test_passed=integration_passed,
            integration_test_log=integration_log,
        )

        return project

    def _write_utils(self, utils_dir: str) -> None:
        metrics_code = '''from __future__ import annotations

import json
from typing import Any, Dict, List


class MetricsCalculator:
    """Calculate experiment metrics."""

    def __init__(self):
        self.results: List[Dict[str, Any]] = []

    def add_step_result(self, step: int, info: Dict[str, Any], grid_result: Dict[str, Any]):
        self.results.append({
            "step": step,
            "p2p_volume_kwh": info.get("total_p2p_volume_kwh", 0.0),
            "grid_import_kwh": info.get("grid_import_kwh", 0.0),
            "grid_export_kwh": info.get("grid_export_kwh", 0.0),
            "min_voltage_pu": grid_result.get("min_voltage_pu", 1.0),
            "max_voltage_pu": grid_result.get("max_voltage_pu", 1.0),
            "voltage_violation_count": grid_result.get("voltage_violation_count", 0),
            "network_loss_kwh": grid_result.get("network_loss_kwh", 0.0),
        })

    def compute_summary(self, total_cost: float) -> Dict[str, Any]:
        if not self.results:
            return {}
        total_p2p = sum(r["p2p_volume_kwh"] for r in self.results)
        total_import = sum(r["grid_import_kwh"] for r in self.results)
        total_export = sum(r["grid_export_kwh"] for r in self.results)
        total_loss = sum(r["network_loss_kwh"] for r in self.results)
        voltage_violations = sum(r["voltage_violation_count"] for r in self.results)
        min_v = min(r["min_voltage_pu"] for r in self.results)
        max_v = max(r["max_voltage_pu"] for r in self.results)
        return {
            "total_cost": total_cost,
            "total_p2p_volume_kwh": total_p2p,
            "total_grid_import_kwh": total_import,
            "total_grid_export_kwh": total_export,
            "total_network_loss_kwh": total_loss,
            "min_voltage_pu": min_v,
            "max_voltage_pu": max_v,
            "total_voltage_violations": voltage_violations,
            "n_steps": len(self.results),
        }

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"results": self.results}, f, indent=2)
'''
        with open(os.path.join(utils_dir, "metrics.py"), "w", encoding="utf-8") as f:
            f.write(metrics_code)

    def _write_configs(
        self,
        config_dir: str,
        grid_case: str,
        model_spec: P2PModelSpec,
        innovation_spec: DetailedInnovationSpec,
        experiment_config: Optional[Dict[str, Any]],
    ) -> None:
        ieee_config = {
            "grid_case": grid_case,
            "bus_count": 33 if grid_case == "ieee33" else 69,
            "base_kv": 12.66,
            "voltage_limits": [0.95, 1.05],
            "substation_bus": 0,
        }
        with open(os.path.join(config_dir, f"{grid_case}_config.json"), "w", encoding="utf-8") as f:
            json.dump(ieee_config, f, indent=2)

        exp_config = experiment_config or {
            "prosumer_count": 8,
            "horizon_hours": 24,
            "grid_case": grid_case,
            "random_seed": 42,
            "n_episodes": 100,
            "log_interval": 10,
        }
        with open(os.path.join(config_dir, "experiment_config.json"), "w", encoding="utf-8") as f:
            json.dump(exp_config, f, indent=2)

        with open(os.path.join(config_dir, "model_spec.json"), "w", encoding="utf-8") as f:
            json.dump(to_dict(model_spec), f, indent=2, ensure_ascii=False)

        with open(os.path.join(config_dir, "innovation_spec.json"), "w", encoding="utf-8") as f:
            json.dump(to_dict(innovation_spec), f, indent=2, ensure_ascii=False)

        smoke_config = dict(exp_config)
        smoke_config["horizon_hours"] = 4
        smoke_config["n_episodes"] = 5
        smoke_config["prosumer_count"] = min(smoke_config.get("prosumer_count", 8), 4)
        smoke_config["log_interval"] = 1
        with open(os.path.join(config_dir, "smoke_config.json"), "w", encoding="utf-8") as f:
            json.dump(smoke_config, f, indent=2)

    def _write_runner(
        self,
        src_dir: str,
        innovation_spec: DetailedInnovationSpec,
        grid_case: str,
    ) -> None:
        algo_family = innovation_spec.base_algorithm_family
        is_rl = algo_family in ("RL", "RL/MARL")
        is_opt = algo_family == "Optimization"
        is_auction = algo_family == "Auction"
        is_game = algo_family == "Game Theory"

        if is_rl:
            runner_code = self._rl_runner_code()
        elif is_opt:
            runner_code = self._optimization_runner_code()
        elif is_auction:
            runner_code = self._auction_runner_code()
        elif is_game:
            runner_code = self._game_runner_code()
        else:
            runner_code = self._rl_runner_code()

        with open(os.path.join(src_dir, "run_experiment.py"), "w", encoding="utf-8") as f:
            f.write(runner_code)

    def _rl_runner_code(self) -> str:
        return '''"""Experiment runner for RL-based P2P energy trading.

Generated by Energy Trading Lab - Paper-to-Code System.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from algorithm.agent import QLearningAgent
from algorithm.reward import RewardCalculator
from algorithm.training_loop import TrainingLoop
from grid.grid_model import GridModel
from market.market_env import MarketEnvironment
from utils.metrics import MetricsCalculator


def load_config(config_path: str) -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def run_experiment(config: dict, progress_callback=None) -> dict:
    grid_case = config.get("grid_case", "ieee33")
    prosumer_count = config.get("prosumer_count", 8)
    horizon_hours = config.get("horizon_hours", 24)
    n_episodes = config.get("n_episodes", 100)
    random_seed = config.get("random_seed", 42)
    log_interval = config.get("log_interval", 10)

    env = MarketEnvironment(
        prosumer_count=prosumer_count,
        horizon_hours=horizon_hours,
        grid_case=grid_case,
        random_seed=random_seed,
    )

    grid = GridModel(grid_case=grid_case)
    reward_calc = RewardCalculator()

    agents = []
    for i in range(prosumer_count):
        agent = QLearningAgent(
            agent_id=i,
            state_size=5,
            action_size=25,
            learning_rate=0.1,
            gamma=0.95,
            epsilon=0.18,
            random_seed=random_seed + i,
        )
        agents.append(agent)

    training = TrainingLoop(
        env=env,
        agents=agents,
        n_episodes=n_episodes,
        log_interval=log_interval,
        progress_callback=progress_callback,
    )

    start_time = time.perf_counter()
    result = training.run()
    elapsed = time.perf_counter() - start_time

    metrics = MetricsCalculator()
    state = env.reset()
    total_cost = 0.0
    done = False
    step = 0

    for agent in agents:
        agent.epsilon = 0.0

    while not done:
        actions = {}
        for agent in agents:
            prosumer_state = training._get_prosumer_state(state, agent.agent_id)
            action = agent.select_action(prosumer_state)
            actions[agent.agent_id] = action

        next_state, rewards, done, info = env.step(actions)
        grid_state = env.get_grid_state()
        grid_result = grid.run_power_flow(
            grid_state["load_profile"],
            grid_state["pv_profile"],
        )
        total_cost += rewards.get("total_cost", 0.0)
        metrics.add_step_result(step, info, grid_result)
        state = next_state
        step += 1

    summary = metrics.compute_summary(total_cost)
    summary["training_elapsed_sec"] = elapsed
    summary["total_episodes"] = result.get("total_episodes", n_episodes)
    summary["final_epsilon"] = result.get("final_epsilon", 0.0)

    return summary


def emit_progress(payload: dict) -> None:
    print("ETL_PROGRESS " + json.dumps(payload, ensure_ascii=False), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run P2P energy trading experiment")
    parser.add_argument("--config", default="configs/experiment_config.json")
    parser.add_argument("--output-dir", default="outputs/results")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    config_path = PROJECT_ROOT / args.config if not os.path.isabs(args.config) else Path(args.config)
    output_dir = PROJECT_ROOT / args.output_dir if not os.path.isabs(args.output_dir) else Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(str(config_path))
    progress = None if args.quiet else emit_progress

    result = run_experiment(config, progress_callback=progress)

    with open(output_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    best = result.get("total_cost", 0.0)
    print(json.dumps({
        "status": "ok",
        "total_cost": best,
        "output_dir": str(output_dir),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''

    def _optimization_runner_code(self) -> str:
        return '''"""Experiment runner for Optimization-based P2P energy trading.

Generated by Energy Trading Lab - Paper-to-Code System.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from algorithm.optimizer import OptimizationSolver
from grid.grid_model import GridModel
from market.market_env import MarketEnvironment
from utils.metrics import MetricsCalculator


def load_config(config_path: str) -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def run_experiment(config: dict, progress_callback=None) -> dict:
    grid_case = config.get("grid_case", "ieee33")
    prosumer_count = config.get("prosumer_count", 8)
    horizon_hours = config.get("horizon_hours", 24)
    random_seed = config.get("random_seed", 42)

    env = MarketEnvironment(
        prosumer_count=prosumer_count,
        horizon_hours=horizon_hours,
        grid_case=grid_case,
        random_seed=random_seed,
    )

    grid = GridModel(grid_case=grid_case)
    solver = OptimizationSolver()

    metrics = MetricsCalculator()
    state = env.reset()
    total_cost = 0.0
    done = False
    step = 0
    start_time = time.perf_counter()

    while not done:
        market_state = {
            "prosumers": state.get("prosumers", []),
            "grid_buy_price": state.get("grid_buy_price", 0.12),
            "grid_sell_price": state.get("grid_sell_price", 0.06),
            "hour": state.get("hour_of_day", 0),
        }
        solution = solver.solve(market_state)

        actions = {}
        for trade in solution.get("trades", []):
            pass

        next_state, rewards, done, info = env.step(actions)
        grid_state = env.get_grid_state()
        grid_result = grid.run_power_flow(
            grid_state["load_profile"],
            grid_state["pv_profile"],
        )
        total_cost += solution.get("total_cost", rewards.get("total_cost", 0.0))
        metrics.add_step_result(step, info, grid_result)
        state = next_state
        step += 1

        if progress_callback and step % 4 == 0:
            progress_callback({
                "event": "optimization_progress",
                "step": step,
                "total_cost": total_cost,
                "elapsed_sec": time.perf_counter() - start_time,
            })

    elapsed = time.perf_counter() - start_time
    summary = metrics.compute_summary(total_cost)
    summary["elapsed_sec"] = elapsed
    summary["objective_value"] = solver.get_objective_value()

    return summary


def emit_progress(payload: dict) -> None:
    print("ETL_PROGRESS " + json.dumps(payload, ensure_ascii=False), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run P2P energy trading experiment")
    parser.add_argument("--config", default="configs/experiment_config.json")
    parser.add_argument("--output-dir", default="outputs/results")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    config_path = PROJECT_ROOT / args.config if not os.path.isabs(args.config) else Path(args.config)
    output_dir = PROJECT_ROOT / args.output_dir if not os.path.isabs(args.output_dir) else Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(str(config_path))
    progress = None if args.quiet else emit_progress

    result = run_experiment(config, progress_callback=progress)

    with open(output_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(json.dumps({
        "status": "ok",
        "total_cost": result.get("total_cost", 0.0),
        "output_dir": str(output_dir),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''

    def _auction_runner_code(self) -> str:
        return '''"""Experiment runner for Auction-based P2P energy trading.

Generated by Energy Trading Lab - Paper-to-Code System.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from algorithm.auction_engine import DoubleAuctionEngine
from grid.grid_model import GridModel
from market.market_env import MarketEnvironment
from utils.metrics import MetricsCalculator


def load_config(config_path: str) -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def run_experiment(config: dict, progress_callback=None) -> dict:
    grid_case = config.get("grid_case", "ieee33")
    prosumer_count = config.get("prosumer_count", 8)
    horizon_hours = config.get("horizon_hours", 24)
    random_seed = config.get("random_seed", 42)

    env = MarketEnvironment(
        prosumer_count=prosumer_count,
        horizon_hours=horizon_hours,
        grid_case=grid_case,
        random_seed=random_seed,
    )

    grid = GridModel(grid_case=grid_case)
    auction = DoubleAuctionEngine(price_rule="midpoint")

    metrics = MetricsCalculator()
    state = env.reset()
    total_cost = 0.0
    done = False
    step = 0
    start_time = time.perf_counter()

    while not done:
        auction.reset()
        prosumers = state.get("prosumers", [])
        buy_price = state.get("grid_buy_price", 0.12)
        sell_price = state.get("grid_sell_price", 0.06)

        for p in prosumers:
            pid = p["id"]
            net_load = p.get("net_load_kw", 0)
            if net_load > 0:
                auction.submit_bid({
                    "prosumer_id": pid,
                    "price": buy_price * 0.95,
                    "quantity": net_load,
                    "timestamp": step,
                })
            elif net_load < 0:
                auction.submit_ask({
                    "prosumer_id": pid,
                    "price": sell_price * 1.05,
                    "quantity": -net_load,
                    "timestamp": step,
                })

        result = auction.clear_market()

        actions = {}
        for trade in result.get("trades", []):
            pass

        next_state, rewards, done, info = env.step(actions)
        grid_state = env.get_grid_state()
        grid_result = grid.run_power_flow(
            grid_state["load_profile"],
            grid_state["pv_profile"],
        )
        total_cost += rewards.get("total_cost", 0.0)
        metrics.add_step_result(step, info, grid_result)
        state = next_state
        step += 1

        if progress_callback and step % 4 == 0:
            progress_callback({
                "event": "auction_progress",
                "step": step,
                "total_cost": total_cost,
                "clearing_price": result.get("clearing_price", 0.0),
                "elapsed_sec": time.perf_counter() - start_time,
            })

    elapsed = time.perf_counter() - start_time
    summary = metrics.compute_summary(total_cost)
    summary["elapsed_sec"] = elapsed

    return summary


def emit_progress(payload: dict) -> None:
    print("ETL_PROGRESS " + json.dumps(payload, ensure_ascii=False), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run P2P energy trading experiment")
    parser.add_argument("--config", default="configs/experiment_config.json")
    parser.add_argument("--output-dir", default="outputs/results")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    config_path = PROJECT_ROOT / args.config if not os.path.isabs(args.config) else Path(args.config)
    output_dir = PROJECT_ROOT / args.output_dir if not os.path.isabs(args.output_dir) else Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(str(config_path))
    progress = None if args.quiet else emit_progress

    result = run_experiment(config, progress_callback=progress)

    with open(output_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(json.dumps({
        "status": "ok",
        "total_cost": result.get("total_cost", 0.0),
        "output_dir": str(output_dir),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''

    def _game_runner_code(self) -> str:
        return '''"""Experiment runner for Game Theory-based P2P energy trading.

Generated by Energy Trading Lab - Paper-to-Code System.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from algorithm.game_engine import StackelbergGameEngine
from grid.grid_model import GridModel
from market.market_env import MarketEnvironment
from utils.metrics import MetricsCalculator


def load_config(config_path: str) -> dict:
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def run_experiment(config: dict, progress_callback=None) -> dict:
    grid_case = config.get("grid_case", "ieee33")
    prosumer_count = config.get("prosumer_count", 8)
    horizon_hours = config.get("horizon_hours", 24)
    random_seed = config.get("random_seed", 42)

    env = MarketEnvironment(
        prosumer_count=prosumer_count,
        horizon_hours=horizon_hours,
        grid_case=grid_case,
        random_seed=random_seed,
    )

    grid = GridModel(grid_case=grid_case)
    game = StackelbergGameEngine(n_followers=max(prosumer_count - 1, 1), leader_id=0)

    metrics = MetricsCalculator()
    state = env.reset()
    total_cost = 0.0
    done = False
    step = 0
    start_time = time.perf_counter()

    while not done:
        market_state = {
            "prosumers": state.get("prosumers", []),
            "grid_buy_price": state.get("grid_buy_price", 0.12),
            "grid_sell_price": state.get("grid_sell_price", 0.06),
        }

        eq_result = game.find_equilibrium(market_state)
        eq_price = eq_result.get("equilibrium_price", 0.1)

        actions = {}
        for i in range(prosumer_count):
            actions[i] = {"bid_price": eq_price, "battery_kw": 0.0}

        next_state, rewards, done, info = env.step(actions)
        grid_state = env.get_grid_state()
        grid_result = grid.run_power_flow(
            grid_state["load_profile"],
            grid_state["pv_profile"],
        )
        total_cost += rewards.get("total_cost", 0.0)
        metrics.add_step_result(step, info, grid_result)
        state = next_state
        step += 1

        if progress_callback and step % 4 == 0:
            progress_callback({
                "event": "game_progress",
                "step": step,
                "total_cost": total_cost,
                "equilibrium_price": eq_price,
                "elapsed_sec": time.perf_counter() - start_time,
            })

    elapsed = time.perf_counter() - start_time
    summary = metrics.compute_summary(total_cost)
    summary["elapsed_sec"] = elapsed

    return summary


def emit_progress(payload: dict) -> None:
    print("ETL_PROGRESS " + json.dumps(payload, ensure_ascii=False), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run P2P energy trading experiment")
    parser.add_argument("--config", default="configs/experiment_config.json")
    parser.add_argument("--output-dir", default="outputs/results")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    config_path = PROJECT_ROOT / args.config if not os.path.isabs(args.config) else Path(args.config)
    output_dir = PROJECT_ROOT / args.output_dir if not os.path.isabs(args.output_dir) else Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config = load_config(str(config_path))
    progress = None if args.quiet else emit_progress

    result = run_experiment(config, progress_callback=progress)

    with open(output_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(json.dumps({
        "status": "ok",
        "total_cost": result.get("total_cost", 0.0),
        "output_dir": str(output_dir),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''

    def _write_requirements(self, project_dir: str) -> None:
        reqs = """pandapower>=2.10.0
numpy>=1.21.0
"""
        with open(os.path.join(project_dir, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write(reqs)

    def _write_readme(
        self,
        project_dir: str,
        model_spec: P2PModelSpec,
        innovation_spec: DetailedInnovationSpec,
        grid_case: str,
    ) -> None:
        title = getattr(model_spec, "title", "P2P Energy Trading Experiment")
        mode = innovation_spec.innovation_mode
        base_algo = innovation_spec.base_algorithm
        n_innovations = len(innovation_spec.layered_innovations)

        readme = f"""# {title}

Generated by Energy Trading Lab - Paper-to-Code System.

## Algorithm Summary

- **Algorithm type**: {innovation_spec.base_algorithm_family}
- **Innovation mode**: {mode}
- **Base algorithm**: {base_algo}
- **Number of innovations**: {n_innovations}
- **Grid case**: {grid_case}

## Project Structure

- `src/grid/` - IEEE 33/69 grid model with pandapower
- `src/market/` - P2P market environment
- `src/algorithm/` - Paper-specific algorithm implementation
- `src/utils/` - Utilities (metrics, etc.)
- `src/run_experiment.py` - Main experiment runner
- `configs/` - Configuration files
- `tests/` - Test files
- `outputs/` - Experiment outputs

## Installation

```bash
pip install -r requirements.txt
```

## Usage

Run full experiment:

```bash
python src/run_experiment.py --config configs/experiment_config.json --output-dir outputs/results
```

Run smoke test:

```bash
python src/run_experiment.py --config configs/smoke_config.json --output-dir outputs/smoke --quiet
```

## Innovations

"""
        for i, inv in enumerate(innovation_spec.layered_innovations, 1):
            readme += f"{i}. **{inv.layer}**: {inv.description}\n"
            readme += f"   - Code change: {inv.code_change_hint}\n\n"

        readme += f"""## Pseudocode

```
{innovation_spec.pseudocode}
```
"""
        with open(os.path.join(project_dir, "README.md"), "w", encoding="utf-8") as f:
            f.write(readme)

    def _write_tests(
        self,
        tests_dir: str,
        innovation_spec: DetailedInnovationSpec,
        grid_case: str,
    ) -> None:
        test_code = f'''"""Smoke test for the generated project."""
from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path


class ProjectSmokeTest(unittest.TestCase):
    def test_smoke_experiment_runs(self):
        project_root = Path(__file__).resolve().parents[1]
        output_dir = project_root / "outputs" / "test_smoke"
        runner = project_root / "src" / "run_experiment.py"
        config = project_root / "configs" / "smoke_config.json"

        completed = subprocess.run(
            [sys.executable, str(runner), "--config", str(config), "--output-dir", str(output_dir), "--quiet"],
            cwd=project_root,
            capture_output=True,
            text=True,
            timeout=120,
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)

        metrics_path = output_dir / "metrics.json"
        self.assertTrue(metrics_path.exists(), "metrics.json not found")

        with open(metrics_path, "r", encoding="utf-8") as f:
            metrics = json.load(f)

        self.assertIn("total_cost", metrics)
        self.assertIn("total_p2p_volume_kwh", metrics)
        self.assertIsInstance(metrics["total_cost"], float)


class GridModelTest(unittest.TestCase):
    def test_grid_model_runs(self):
        project_root = Path(__file__).resolve().parents[1]
        sys.path.insert(0, str(project_root / "src"))
        from grid.grid_model import GridModel

        model = GridModel(grid_case="{grid_case}")
        result = model.run_power_flow({{0: 10.0, 1: 5.0}}, {{0: 2.0, 1: 3.0}})
        self.assertIn("min_voltage_pu", result)
        self.assertIn("max_voltage_pu", result)


if __name__ == "__main__":
    unittest.main()
'''
        with open(os.path.join(tests_dir, "test_smoke.py"), "w", encoding="utf-8") as f:
            f.write(test_code)

    def _run_integration_test(
        self,
        project_dir: str,
        innovation_spec: DetailedInnovationSpec,
    ) -> tuple[bool, str]:
        """Run integration smoke test on the assembled project."""
        project_dir = os.path.abspath(project_dir)
        runner_path = os.path.join(project_dir, "src", "run_experiment.py")
        config_path = os.path.join(project_dir, "configs", "smoke_config.json")
        output_dir = os.path.join(project_dir, "outputs", "integration_test")

        if not os.path.exists(runner_path):
            return False, "Runner script not found"

        try:
            result = subprocess.run(
                [sys.executable, runner_path, "--config", config_path, "--output-dir", output_dir, "--quiet"],
                cwd=project_dir,
                capture_output=True,
                text=True,
                timeout=60,
                env={**os.environ, "PYTHONPATH": os.path.join(project_dir, "src") + os.pathsep + os.environ.get("PYTHONPATH", "")},
            )
            log = f"STDOUT:\n{result.stdout}\n\nSTDERR:\n{result.stderr}"
            if result.returncode != 0:
                return False, log
            return True, log
        except subprocess.TimeoutExpired:
            return False, "Integration test timed out"
        except Exception as e:
            return False, f"Integration test error: {str(e)}"
