from __future__ import annotations

import os
import re
import shutil
from typing import Any, Dict, List

from .schemas import ExperimentRecipe, to_dict
from .utils import ensure_dir, write_json, write_text


def build_code_project(
    run_dir: str,
    run_id: str,
    source_type: str,
    model_spec: Any,
    strategies: Any,
    innovation: Any,
    gaps: Any,
    hypotheses: Any,
    recipe: ExperimentRecipe,
    metrics: Any,
    executions: List[Any],
    analysis_meta: Dict[str, Any],
) -> Dict[str, str]:
    project_dir = ensure_dir(os.path.join(run_dir, "code_project"))
    package_dir = ensure_dir(os.path.join(project_dir, "src", "energy_project"))
    config_dir = ensure_dir(os.path.join(project_dir, "configs"))
    tests_dir = ensure_dir(os.path.join(project_dir, "tests"))
    outputs_dir = ensure_dir(os.path.join(project_dir, "outputs"))
    ensure_dir(os.path.join(project_dir, "docs"))

    write_json(os.path.join(config_dir, "experiment_config.json"), to_dict(recipe))
    write_json(os.path.join(config_dir, "smoke_config.json"), _smoke_recipe_payload(recipe))
    write_json(os.path.join(config_dir, "model_spec.json"), to_dict(model_spec))
    write_json(os.path.join(config_dir, "strategy_spec.json"), to_dict(strategies))
    write_json(os.path.join(config_dir, "innovation_spec.json"), to_dict(innovation))
    write_json(os.path.join(config_dir, "hypotheses.json"), to_dict(hypotheses))
    write_json(os.path.join(config_dir, "analysis_meta.json"), analysis_meta)
    write_json(os.path.join(config_dir, "baseline_metrics.json"), to_dict(metrics))
    write_json(os.path.join(config_dir, "reproduction_gaps.json"), to_dict(gaps))

    final_script = executions[-1].script_path if executions else ""
    if final_script and os.path.exists(final_script):
        shutil.copyfile(final_script, os.path.join(package_dir, "generated_attempt.py"))

    title = getattr(model_spec, "title", "Energy trading experiment")
    write_text(os.path.join(project_dir, "README.md"), _render_project_readme(run_id, source_type, title, recipe, innovation))
    write_text(os.path.join(project_dir, "requirements.txt"), _render_requirements())
    write_text(os.path.join(project_dir, "pyproject.toml"), _render_pyproject())
    write_text(os.path.join(package_dir, "__init__.py"), '"""Generated Energy Trading Lab project package."""\n')
    write_text(os.path.join(package_dir, "adapter.py"), _render_adapter_py())
    write_text(os.path.join(package_dir, "run_experiment.py"), _render_runner_py())
    write_text(os.path.join(tests_dir, "test_smoke.py"), _render_smoke_test())
    write_text(os.path.join(outputs_dir, ".gitkeep"), "")

    return {
        "code_project": project_dir,
        "code_project_readme": os.path.join(project_dir, "README.md"),
        "code_project_runner": os.path.join(package_dir, "run_experiment.py"),
        "code_project_adapter": os.path.join(package_dir, "adapter.py"),
        "code_project_config": os.path.join(config_dir, "experiment_config.json"),
        "code_project_smoke_config": os.path.join(config_dir, "smoke_config.json"),
        "code_project_test": os.path.join(tests_dir, "test_smoke.py"),
    }


def _smoke_recipe_payload(recipe: ExperimentRecipe) -> Dict[str, Any]:
    payload = to_dict(recipe)
    payload["name"] = str(payload.get("name", "experiment")) + "-smoke"
    payload["horizon_hours"] = min(int(payload.get("horizon_hours", 24)), 8)
    payload["prosumer_count"] = min(int(payload.get("prosumer_count", 8)), 8)
    payload["training_episodes"] = min(int(payload.get("training_episodes", 100)), 8)
    payload["training_log_interval"] = 2
    payload["experiment_depth"] = "smoke"
    payload["strategies"] = _smoke_strategies(list(payload.get("strategies", [])))
    return payload


def _smoke_strategies(strategies: List[str]) -> List[str]:
    selected = ["no_trading"]
    for strategy in strategies:
        if strategy in ("rule_double_auction", "optimization_clearing", "rl_bidding", "proposed_method"):
            selected.append(strategy)
        if len(selected) >= 4:
            break
    return list(dict.fromkeys(selected))


def _render_project_readme(run_id: str, source_type: str, title: str, recipe: ExperimentRecipe, innovation: Any) -> str:
    innovation_type = getattr(innovation, "innovation_type", "paper-specific adapter")
    safe_title = re.sub(r"\s+", " ", title).strip()
    return f"""# {safe_title}

This is a dedicated code project generated by Energy Trading Lab.

- Run id: `{run_id}`
- Source type: `{source_type}`
- Grid case: `{recipe.grid_case}`
- Experiment depth: `{recipe.experiment_depth}`
- Horizon: `{recipe.horizon_hours}` hours
- RL episodes: `{recipe.training_episodes}`
- Paper/theory adapter: `{innovation_type}`

## Project Layout

- `configs/experiment_config.json`: full experiment configuration generated for this paper/theory.
- `configs/smoke_config.json`: short configuration for a fast local check.
- `configs/innovation_spec.json`: extracted algorithm modifications and reward/objective terms.
- `src/energy_project/adapter.py`: project-specific adapter that injects this paper/theory's algorithm changes.
- `src/energy_project/run_experiment.py`: runnable experiment entrypoint.
- `src/energy_project/generated_attempt.py`: final generated attempt script kept for audit, when available.
- `tests/test_smoke.py`: smoke test for this project.
- `outputs/`: local experiment outputs.

## Run

From this directory:

```bash
python src/energy_project/run_experiment.py --config configs/experiment_config.json --output-dir outputs/research
```

Fast smoke check:

```bash
python src/energy_project/run_experiment.py --config configs/smoke_config.json --output-dir outputs/smoke
python -m unittest discover -s tests
```

If you move this folder outside the original repository, set:

```bash
export ENERGY_TRADING_LAB_REPO=/absolute/path/to/Energy-Trading-Lab
```
"""


def _render_requirements() -> str:
    return """# This project uses the parent Energy Trading Lab engine.
# From the original repository root, the existing .venv is enough.
# If moved elsewhere, install the parent repository or set ENERGY_TRADING_LAB_REPO.
"""


def _render_pyproject() -> str:
    return """[project]
name = "generated-energy-trading-project"
version = "0.1.0"
description = "Dedicated Energy Trading Lab experiment project"
requires-python = ">=3.10"
dependencies = []

[tool.energy-trading-lab]
generated = true
"""


def _render_adapter_py() -> str:
    return '''from __future__ import annotations

import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = PROJECT_ROOT / "configs"


def load_project_json(filename: str) -> dict:
    with open(CONFIG_DIR / filename, "r", encoding="utf-8") as handle:
        return json.load(handle)


def apply_project_adapter(recipe):
    """Apply the paper/theory-specific algorithm changes for this project."""

    innovation = load_project_json("innovation_spec.json")
    params = dict(innovation.get("strategy_parameters", {}))
    recipe.strategy_parameters.update(params)

    innovation_type = innovation.get("innovation_type")
    if innovation_type and innovation_type not in recipe.innovation_tags:
        recipe.innovation_tags.append(innovation_type)

    if innovation.get("code_modifications") and "proposed_method" not in recipe.strategies:
        recipe.strategies.append("proposed_method")

    reward_terms = ", ".join(innovation.get("custom_reward_terms", []))
    recipe.notes = (
        recipe.notes
        + " Dedicated project adapter: "
        + str(innovation_type or "custom")
        + ("; reward/objective terms: " + reward_terms if reward_terms else "")
    ).strip()
    return recipe
'''


def _render_runner_py() -> str:
    return '''from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))


def add_lab_repo_to_path() -> None:
    env_repo = os.environ.get("ENERGY_TRADING_LAB_REPO")
    candidates = [Path(env_repo)] if env_repo else []
    candidates.append(Path.cwd())
    candidates.extend(Path(__file__).resolve().parents)
    for candidate in candidates:
        if candidate and (candidate / "p2plab").is_dir():
            sys.path.insert(0, str(candidate))
            return


add_lab_repo_to_path()

from energy_project.adapter import apply_project_adapter  # noqa: E402
from p2plab.schemas import ExperimentRecipe, to_dict  # noqa: E402
from p2plab.simulation import run_experiment_detailed  # noqa: E402


def recipe_from_dict(data: dict) -> ExperimentRecipe:
    return ExperimentRecipe(
        name=data["name"],
        grid_case=data["grid_case"],
        horizon_hours=int(data["horizon_hours"]),
        prosumer_count=int(data["prosumer_count"]),
        strategies=list(data["strategies"]),
        random_seed=int(data["random_seed"]),
        training_episodes=int(data["training_episodes"]),
        voltage_limits=list(data["voltage_limits"]),
        notes=data.get("notes", ""),
        innovation_tags=list(data.get("innovation_tags", [])),
        strategy_parameters=dict(data.get("strategy_parameters", {})),
        experiment_depth=data.get("experiment_depth", "quick"),
        training_log_interval=int(data.get("training_log_interval", 50)),
    )


def emit_progress(payload: dict) -> None:
    print("ETL_PROGRESS " + json.dumps(payload, ensure_ascii=False), flush=True)


def write_outputs(output_dir: Path, metrics, hourly_rows, training_rows) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "metrics.json", "w", encoding="utf-8") as handle:
        json.dump(to_dict(metrics), handle, ensure_ascii=False, indent=2)
    with open(output_dir / "hourly_metrics.json", "w", encoding="utf-8") as handle:
        json.dump(hourly_rows, handle, ensure_ascii=False, indent=2)
    with open(output_dir / "training_curve.json", "w", encoding="utf-8") as handle:
        json.dump(training_rows, handle, ensure_ascii=False, indent=2)
    best = min(metrics, key=lambda item: item.total_cost)
    with open(output_dir / "summary.md", "w", encoding="utf-8") as handle:
        handle.write("# Experiment Summary\\n\\n")
        handle.write(f"- Best strategy: `{best.strategy}`\\n")
        handle.write(f"- Total cost: `{best.total_cost}`\\n")
        handle.write(f"- P2P volume: `{best.p2p_volume_kwh}` kWh\\n")
        handle.write(f"- Training episodes: `{best.training_episodes}`\\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run this dedicated Energy Trading Lab project.")
    parser.add_argument("--config", default="configs/experiment_config.json")
    parser.add_argument("--output-dir", default="outputs/research")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    with open(args.config, "r", encoding="utf-8") as handle:
        recipe = recipe_from_dict(json.load(handle))
    recipe = apply_project_adapter(recipe)
    progress = None if args.quiet else emit_progress
    metrics, hourly_rows, training_rows = run_experiment_detailed(recipe, progress_callback=progress)
    write_outputs(Path(args.output_dir), metrics, hourly_rows, training_rows)
    best = min(metrics, key=lambda item: item.total_cost)
    print(json.dumps({"status": "ok", "best_strategy": best.strategy, "output_dir": args.output_dir}, ensure_ascii=False))


if __name__ == "__main__":
    main()
'''


def _render_smoke_test() -> str:
    return '''from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path


class GeneratedProjectSmokeTest(unittest.TestCase):
    def test_smoke_experiment_runs(self):
        project_root = Path(__file__).resolve().parents[1]
        output_dir = project_root / "outputs" / "test_smoke"
        command = [
            sys.executable,
            str(project_root / "src" / "energy_project" / "run_experiment.py"),
            "--config",
            str(project_root / "configs" / "smoke_config.json"),
            "--output-dir",
            str(output_dir),
            "--quiet",
        ]
        completed = subprocess.run(command, cwd=project_root, text=True, capture_output=True, timeout=60)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        with open(output_dir / "metrics.json", "r", encoding="utf-8") as handle:
            metrics = json.load(handle)
        self.assertGreaterEqual(len(metrics), 2)
        self.assertTrue((output_dir / "training_curve.json").exists())


if __name__ == "__main__":
    unittest.main()
'''
